### ISSUE TITLE
Multiple god containers unable to discover each other

### ISSUE THREAD

**Issue by o0n1x** [miguelammatos/Kollaps#52]
Hello, I have an issue running Kollaps iperf3 example on a swarm network with 2 nodes. It seems that the god container in the 2 nodes can’t communicate with each other to start the experiment. 

steps I did to attempt this experiment:
1- installed kollaps on both nodes
2-built all 4 images needed on both nodes ( iperf3-client/ iperf3-server/dashboard/kollaps:2.0) on both nodes (the xml file is on the same working directory)
3-built the yaml file using the topology.xml file in iperf3 example folder
4- ran docker swarm init with advertise-addr.
5-  the second node joined with advertise-addr, and promoted it to manager
6- created the overlay network (sudo docker network create "--driver=overlay" "--subnet=11.1.0.0/20" kollaps_network)
7-  started the experiment (sudo docker stack deploy -c iperf3.yaml fed)

God container log on node 1:
```
[Py (God)] bootstrapping all containers with label 1d57e9fd-33d2-442a-9b7a-685192869877.
[Py (god)] ip: (not yet known), nr. of gods: 2
[Py (god1)] 10.85.181.224 :: ['HELLO', '31292119439190104239643910459301543485']
[Py (god1)] 10.85.181.224 :: ['HELLO', '31292119439190104239643910459301543485']
[Py (god1)] 10.85.181.224 :: ['HELLO', '31292119439190104239643910459301543485']
… repeating 
```

running containers in node 1:

```
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS          PORTS     NAMES
85cd25194aeb   kollaps/iperf3-client:1.0   "/bin/sh -c 'mkfifo …"   5 seconds ago    Up 5 seconds              fed_client3-1d57e9fd-33d2-442a-9b7a-685192869877.1.ughmq77u03996p6mhq4hwk4ht
e07157d82625   kollaps/iperf3-client:1.0   "/bin/sh -c 'mkfifo …"   9 seconds ago    Up 9 seconds              fed_client1-1d57e9fd-33d2-442a-9b7a-685192869877.1.9brfd0sme1cijkuqqqhldxb1v
9d3988678e9a   kollaps/dashboard:1.0       "/bin/bash /dashboar…"   11 seconds ago   Up 10 seconds             fed_dashboard-1d57e9fd-33d2-442a-9b7a-685192869877.1.os20kf0tb5yb6ehzszwcjr4cf
6b1ce9a429a3   ef3b245cb58c                "/usr/bin/pid1 /usr/…"   11 seconds ago   Up 11 seconds             god_4515887774502221465
7ecfddda9897   kollaps:2.0                 "/usr/bin/pid1 /usr/…"   14 seconds ago   Up 13 seconds             fed_bootstrapper.2yuzmkf6qff4i0esf9g5t34ck.wjj47fv0mc1s0xh8sf10tef0b
1127669b58d6   kollaps/iperf3-server:1.0   "/bin/sh -c 'mkfifo …"   15 seconds ago   Up 14 seconds             fed_server-1d57e9fd-33d2-442a-9b7a-685192869877.1.sh5l516xzxqrk6jqsokturf4f
```

God	container log on node 2:
```
bootstrapping all containers with label 1d57e9fd-33d2-442a-9b7a-685192869877.
[Py (god)] ip: (not yet known), nr. of gods: 2
[Py (god1)] 10.85.160.54 :: ['HELLO', '327081733781722103987371202074212566849']
[Py (god1)] 10.85.160.54 :: ['HELLO', '327081733781722103987371202074212566849']
[Py (god1)] 10.85.160.54 :: ['HELLO', '327081733781722103987371202074212566849']
… repeating
```

running containers in node 2:

```
CONTAINER ID   IMAGE                       COMMAND                  CREATED              STATUS              PORTS     NAMES
c515b35ff12a   kollaps/iperf3-client:1.0   "/bin/sh -c 'mkfifo …"   About a minute ago   Up About a minute             fed_client2-1d57e9fd-33d2-442a-9b7a-685192869877.1.yga8epfa4q1gpfnpst5gfql73
916247b19067   b1fc81018fa2                "/usr/bin/pid1 /usr/…"   About a minute ago   Up About a minute             god_12082734498568561274
92a213b53cf6   kollaps:2.0                 "/usr/bin/pid1 /usr/…"   About a minute ago   Up About a minute             fed_bootstrapper.kd5t1ijs8z99u6twi4zaudipf.bfp9l38x63exfkkyghif9ofra
ce7b260e8b06   kollaps/iperf3-server:1.0   "/bin/sh -c 'mkfifo …"   About a minute ago   Up About a minute             fed_server-1d57e9fd-33d2-442a-9b7a-685192869877.2.sp9lj5v9xu0ikagosdaunn42j
d6ec765df8cb   kollaps/iperf3-server:1.0   "/bin/sh -c 'mkfifo …"   About a minute ago   Up About a minute             fed_server-1d57e9fd-33d2-442a-9b7a-685192869877.3.umodh11lfo1ajfjknz9l4lgvh
```

**Comment by sebastiaoamaro** [comment]
Hi @o0n1x, 
Please rebuild the .yaml file with docker swarm already configurated. I am almost certain this is the source of the problem.
If the problem remains please show me the beggining of the .yaml file.

**Comment by o0n1x** [comment]
thank you for the quick response, 
I have rebuilt the yaml file and ran the experiment, but the same problem still persists.

this is the yaml file in the beginning ,before the services:

```
version: "3.3"
services:
  bootstrapper:
    image: kollaps:2.0
    command: ["-s", "5d6ec279-460e-4b50-a3d6-4cba28729a60"]
    deploy:
      mode: global
    environment:
      KOLLAPS_UUID: '5d6ec279-460e-4b50-a3d6-4cba28729a60'
      KOLLAPS_ORCHESTRATOR: swarm
      NUMBER_OF_GODS: 2
      POOL_PERIOD: 0.05
      MAX_FLOW_AGE: 2
    labels:
      boot5d6ec279-460e-4b50-a3d6-4cba28729a60: "true"
    volumes:
      - '/lib/modules:/lib/modules/'
      - '/usr/src:/usr/src/'
      - '/sys/:/sys/'
      - '/home/ubuntu/kollapsTesting/kollaps_w3/Kollaps/examples/iperf3/topology.xml:/topology.xml'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - KollapsNet
```
